# AUTO-GENERATED BY AZURE OPENAI
# REVIEW BEFORE DEPLOYMENT
import pulumi
from pulumi_azure_native import resources, network, compute, storage, web, containerservice, sql, cosmosdb
from pulumi import Config, export

# Configuration
config = Config()
location = config.get("location") or "eastus"
resource_group_name = config.get("resource_group_name") or "pulumi-azure-resources"
tags = {
    "Environment": "Production",
    "ManagedBy": "Pulumi"
}

# Create a Resource Group
resource_group = resources.ResourceGroup(
    "resourcegroup-prod-myapp4-eastus",
    location=location,
    tags=tags
)

# Virtual Network and Subnets
vnet = network.VirtualNetwork(
    "virtualnetwork-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    address_space=network.AddressSpaceArgs(
        address_prefixes=["10.0.0.0/16"],
    ),
    tags=tags
)

subnet1 = network.Subnet(
    "subnet-prod-myapp4-eastus-1",
    resource_group_name=resource_group.name,
    virtual_network_name=vnet.name,
    address_prefix="10.0.1.0/24"
)

subnet2 = network.Subnet(
    "subnet-prod-myapp4-eastus-2",
    resource_group_name=resource_group.name,
    virtual_network_name=vnet.name,
    address_prefix="10.0.2.0/24"
)

# Public IP for Load Balancer
public_ip = network.PublicIPAddress(
    "publicip-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    public_ip_allocation_method=network.IPAllocationMethod.STATIC,
    sku=network.PublicIPAddressSkuArgs(
        name=network.PublicIPAddressSkuName.STANDARD,
    ),
    tags=tags
)

# Load Balancer
load_balancer = network.LoadBalancer(
    "loadbalancer-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    sku=network.LoadBalancerSkuArgs(
        name=network.LoadBalancerSkuName.STANDARD,
    ),
    frontend_ip_configurations=[network.FrontendIPConfigurationArgs(
        name="loadBalancerFrontEnd",
        public_ip_address=network.PublicIPAddressArgs(
            id=public_ip.id,
        ),
    )],
    tags=tags
)

# Storage Account for various storage services
storage_account = storage.StorageAccount(
    "storageapulumi",
    resource_group_name=resource_group.name,
    location=location,
    sku=storage.SkuArgs(
        name=storage.SkuName.STANDARD_LRS,
    ),
    kind=storage.Kind.STORAGE_V2,
    tags=tags
)

# Blob Storage Container
blob_container = storage.BlobContainer(
    "bcprodmyapp",
    account_name=storage_account.name,
    resource_group_name=resource_group.name,
    container_name="data"
)

# File Share
file_share = storage.FileShare(
    "fsprodmyapp",
    account_name=storage_account.name,
    resource_group_name=resource_group.name,
    share_name="files"
)

# Queue
storage_queue = storage.Queue(
    "quprodmyapp",
    account_name=storage_account.name,
    resource_group_name=resource_group.name,
    queue_name="tasks"
)

# Data Lake Storage (using StorageV2 with hierarchical namespace enabled)
data_lake_storage = storage.StorageAccount(
    "dsprodmyapp4us",
    resource_group_name=resource_group.name,
    location=location,
    sku=storage.SkuArgs(
        name=storage.SkuName.STANDARD_LRS,
    ),
    kind=storage.Kind.STORAGE_V2,
    is_hns_enabled=True,
    tags=tags
)

# Virtual Machine
vm = compute.VirtualMachine(
    "vm-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    hardware_profile=compute.HardwareProfileArgs(
        vm_size=compute.VirtualMachineSizeTypes.STANDARD_B1S,
    ),
    os_profile=compute.OSProfileArgs(
        computer_name="examplevm",
        admin_username="adminuser",
        admin_password="P@ssw0rd1234!",  # In production, use a secret or Key Vault
    ),
    storage_profile=compute.StorageProfileArgs(
        image_reference=compute.ImageReferenceArgs(
            publisher="Canonical",
            offer="UbuntuServer",
            sku="18.04-LTS",
            version="latest",
        ),
        os_disk=compute.OSDiskArgs(
            create_option=compute.DiskCreateOption.FROM_IMAGE,
            name="myosdisk",
        ),
    ),
    network_profile=compute.NetworkProfileArgs(
        network_interfaces=[compute.NetworkInterfaceReferenceArgs(
            id=network.NetworkInterface(
                "networkinterface-prod-myapp4-eastus",
                resource_group_name=resource_group.name,
                location=location,
                ip_configurations=[network.NetworkInterfaceIPConfigurationArgs(
                    name="example-ipconfig",
                    subnet=network.SubnetArgs(id=subnet1.id),
                )],
                tags=tags
            ).id,
        )],
    ),
    tags=tags
)

# Azure Kubernetes Service (AKS)
aks_cluster = containerservice.ManagedCluster(
    "aks-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    agent_pool_profiles=[containerservice.ManagedClusterAgentPoolProfileArgs(
        count=1,
        max_pods=50,
        mode="System",
        name="agentpool",
        node_labels={},
        os_disk_size_gb=30,
        os_type="Linux",
        type="VirtualMachineScaleSets",
        vm_size="Standard_B2s",
    )],
    dns_prefix="akscluster",
    enable_rbac=True,
    kubernetes_version="1.32.1",
    node_resource_group="aks-node-resources",
    identity=containerservice.ManagedClusterIdentityArgs(
        type="SystemAssigned"
    ),
    tags=tags
)

# App Service Plan
app_service_plan = web.AppServicePlan(
    "appserviceplan-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    kind="Linux",
    reserved=True,  # Must be true for Linux
    sku=web.SkuDescriptionArgs(
        name="B1",
        tier="Basic",
    ),
    tags=tags
)

# App Service
app_service = web.WebApp(
    "appservice-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    server_farm_id=app_service_plan.id,
    site_config=web.SiteConfigArgs(
        linux_fx_version="NODE|14-lts",
    ),
    tags=tags
)

# Storage Account for Functions
storage_account_function = storage.StorageAccount(
    "fsprodmyapp4eu",
    resource_group_name=resource_group.name,
    location=location,
    sku=storage.SkuArgs(name=storage.SkuName.STANDARD_LRS),
    kind=storage.Kind.STORAGE_V2,
    tags=tags
)

# Get storage keys
storage_keys = storage.list_storage_account_keys_output(
    account_name=storage_account_function.name,
    resource_group_name=resource_group.name
)

# Construct connection string
connection_string = pulumi.Output.all(
    storage_account_function.name,
    storage_keys.keys[0].value
).apply(
    lambda args: f"DefaultEndpointsProtocol=https;AccountName={args[0]};AccountKey={args[1]};EndpointSuffix=core.windows.net"
)

# Function App
function_app = web.WebApp(
    "functionapp-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    server_farm_id=app_service_plan.id,
    kind="functionapp",
    site_config=web.SiteConfigArgs(
        app_settings=[
            web.NameValuePairArgs(
                name="AzureWebJobsStorage",
                value=connection_string,
            ),
            web.NameValuePairArgs(
                name="FUNCTIONS_WORKER_RUNTIME",
                value="python",
            ),
            web.NameValuePairArgs(
                name="FUNCTIONS_EXTENSION_VERSION",
                value="~4",
            ),
        ],
    ),
    tags=tags
)

# Azure SQL Database
sql_server = sql.Server(
    "sqlserver-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    administrator_login=config.get("sqlAdmin") or "sqladmin",
    administrator_login_password=config.get_secret("sqlPassword") or "P@ssw0rd1234!",  # Use secrets in production
    version="12.0",
    tags=tags
)

sql_database = sql.Database(
    "sqldatabase-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    server_name=sql_server.name,
    sku=sql.SkuArgs(
        name="S0",
        tier="Standard",
    ),
    tags=tags
)

# Cosmos DB
cosmos_account = cosmosdb.DatabaseAccount(
    "cosmosaccount-prod-myapp4-eastus",
    resource_group_name=resource_group.name,
    location=location,
    database_account_offer_type="Standard",
    locations=[cosmosdb.LocationArgs(
        location_name=location,
        failover_priority=0,
    )],
    consistency_policy=cosmosdb.ConsistencyPolicyArgs(
        default_consistency_level="Session",
    ),
    tags=tags
)

cosmos_db = cosmosdb.SqlResourceSqlDatabase(
    "cosmosdb-prod-myapp4-eastus",
    account_name=cosmos_account.name,
    resource_group_name=resource_group.name,
    database_name="cosmos-db",
    resource=cosmosdb.SqlDatabaseResourceArgs(
        id="cosmos-db",
    ),
    options=cosmosdb.CreateUpdateOptionsArgs(
        throughput=400,
    )
)

# Export outputs
export("resource_group_name", resource_group.name)
export("vnet_name", vnet.name)
export("load_balancer_public_ip", public_ip.ip_address)
export("storage_account_name", storage_account.name)
export("vm_name", vm.name)
export("aks_cluster_name", aks_cluster.name)
export("app_service_url", app_service.default_host_name.apply(lambda hostname: f"https://{hostname}"))
export("function_app_url", function_app.default_host_name.apply(lambda hostname: f"https://{hostname}"))
export("sql_server_fqdn", sql_server.fully_qualified_domain_name)
export("cosmos_account_endpoint", cosmos_account.document_endpoint)